#spring configuration
spring:	
   application:
      name: mtsite

   # devtools - live reload   
   devtools:
      livereload:
         enavled: true
         
   #mvc   
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
            
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB

   #messages resource(internationalization, i18n)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: utf-8

   #aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true

   # datasource
   datasource:
       driver-class-name: org.mariadb.jdbc.Driver
       url: jdbc:mariadb://127.0.0.1:3306/webdb?characterEncoding=utf8
       username: webdb
       password: webdb
       hikari:
          minmum-idle: 10
          maxmun-pool-size: 20

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# server
server:
   port: 8899
   servlet:
   context-path: /mysite05
   encoding:
      charset: utf-8
      enabled: true

# logging
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: /${spring.application.name}-logs/exception.%d{yyyy-MM-dd}.%i.log.zip   	
         max-file-size: 200MB
         max-history: 10
   file: /mysite-logs/exception.log
   level:
   root: INFO
   com:
      bitacademy:
         mtsite:
            exception: ERROR